    -- Seed data for Portfolio database
    -- Run this in the Supabase SQL Editor AFTER running schema.sql

    -- 1. Seed Skills
    INSERT INTO skills (name, category, icon, proficiency, display_order, published) VALUES
    ('Python', 'Languages & AI', 'fab fa-python', 90, 10, true),
    ('Machine Learning', 'Artificial Intelligence', 'fas fa-robot', 85, 20, true),
    ('Artificial Intelligence', 'Artificial Intelligence', 'fas fa-brain', 85, 30, true),
    ('Data Science', 'Data Engineering', 'fas fa-chart-line', 80, 40, true),
    ('SQL & RDBMS', 'Databases', 'fas fa-database', 85, 50, true),
    ('AWS Cloud', 'Cloud Computing', 'fab fa-aws', 80, 60, true),
    ('Azure', 'Cloud Computing', 'fab fa-microsoft', 75, 70, true),
    ('HTML/CSS', 'Frontend Development', 'fab fa-html5', 90, 80, true),
    ('JavaScript', 'Frontend Development', 'fab fa-js', 85, 90, true),
    ('Java', 'Languages & AI', 'fab fa-java', 75, 100, true),
    ('Data Visualization', 'Data Engineering', 'fas fa-chart-bar', 80, 110, true),
    ('Algorithm Design', 'Fundamentals', 'fas fa-project-diagram', 85, 120, true),
    ('Deep Learning', 'Artificial Intelligence', 'fas fa-network-wired', 80, 130, true),
    ('Git & GitHub', 'Developer Tools', 'fab fa-git-alt', 85, 140, true);

    -- 2. Seed Certificates
    INSERT INTO certificates (title, issuing_organization, description, credential_url, category, image_url, featured, icon, display_order, published) VALUES
    -- AI & ML Gallery & Featured
    ('Getting Started with Artificial Intelligence', 'IBM SkillsBuild', 'Comprehensive introduction to Artificial Intelligence concepts, ethical AI, and practical applications across industries.', 'https://www.credly.com/badges/de0e7fd4-8593-48c7-95f6-104af1769c4e/linked_in?t=t3kl17', 'AI & Machine Learning', 'assets/certificates/ai-ml/getting-started-ai-ibm-skillsbuild.jpg', true, 'fas fa-robot', 10, true),
    ('Deep Learning using TensorFlow', 'IBM', 'Deep learning concepts including CNNs, RNNs, and autoencoders using TensorFlow.', NULL, 'AI & Machine Learning', 'assets/certificates/ai-ml/deep-learning-tensorflow-ibm.jpg', false, NULL, 20, true),
    ('IBM Watson Services – Rapid Development', 'IBM', 'Job training in building chat widgets and AI services rapidly with IBM Watson.', NULL, 'AI & Machine Learning', 'assets/certificates/ai-ml/ibm-watson-services-rapid-dev.jpg', false, NULL, 30, true),
    ('Introduction to Artificial Intelligence', 'Simplilearn SkillUp', 'Overview of AI techniques, applications, and basic algorithms.', NULL, 'AI & Machine Learning', 'assets/certificates/ai-ml/intro-to-ai-simplilearn.jpg', false, NULL, 40, true),
    ('Introduction to Generative AI Studio', 'Google Cloud + Simplilearn', 'Practical generative AI studio skills using Google Cloud tools.', NULL, 'AI & Machine Learning', 'assets/certificates/ai-ml/intro-generative-ai-studio-google-cloud.jpg', false, NULL, 50, true),
    ('Machine Learning', 'Ethnotech Academy', 'Practical ML training with regression, classification, and clustering implementation.', NULL, 'AI & Machine Learning', 'assets/certificates/ai-ml/machine-learning-ethnotech.jpg', false, NULL, 60, true),
    ('Machine Learning', 'Intel EdGate Technologies', 'Industrial training utilizing Intel solutions and tools for ML.', NULL, 'AI & Machine Learning', 'assets/certificates/ai-ml/machine-learning-intel-edgate.jpg', false, NULL, 70, true),
    ('Predictive Analytics using IBM SPSS Modeler', 'IBM', 'Data mining and predictive analytics modeling using IBM SPSS.', NULL, 'AI & Machine Learning', 'assets/certificates/ai-ml/predictive-analytics-ibm-spss.jpg', false, NULL, 80, true),

    -- Cloud Computing Featured & Gallery
    ('AWS Academy Cloud Foundations', 'AWS Academy', 'Graduate training badge in AWS cloud fundamentals and architecture — covering core services, pricing, and security.', 'https://www.credly.com/badges/850a46b9-cd01-46eb-a853-35550567b86c/linked_in?t=t3kloq', 'Cloud Computing', 'assets/certificates/cloud-computing/aws-academy-cloud-foundations.jpg', true, 'fab fa-aws', 90, true),
    ('Solution Architecture', 'AWS + Forage', 'Job simulation in designing scalable, resilient solution architectures for enterprise-grade systems.', 'https://media.licdn.com/dms/image/v2/D4E22AQEGpdCmKHz7zA/feedshare-shrink_800/B4EZddSqCDHYAg-/0/1749616862439?e=1766620800&v=beta&t=_TCJKrqS71aJvjW24OvR1IKrAknmvRVPPPjzfHIsnjY', 'Cloud Computing', 'assets/certificates/cloud-computing/aws-solutions-architecture-forage.jpg', true, 'fas fa-project-diagram', 100, true),
    ('Journey to Cloud', 'IBM SkillsBuild', 'Envisioning cloud-first solutions, digital transformation strategies, and enterprise architecture design.', 'https://www.credly.com/badges/85e4145d-ecb3-4b8f-bb30-e4e47b4a26cc/linked_in?t=t3kkzf', 'Cloud Computing', 'assets/certificates/cloud-computing/journey-to-cloud-ibm.jpg', true, 'fas fa-cloud', 110, true),
    ('Azure Fundamentals', 'Skillsoft', 'Microsoft Azure cloud computing essentials — virtual machines, storage, networking, and identity management.', 'https://skillsoft.digitalbadges.skillsoft.com/481daa56-525f-46d3-b249-ff884ef8ee85', 'Cloud Computing', 'assets/certificates/cloud-computing/azure-fundamentals-skillsoft.jpg', true, 'fab fa-microsoft', 120, true),
    ('Microsoft Azure Fundamentals', 'Infosys Springboard', 'Microsoft Azure cloud computing foundations and services overview.', NULL, 'Cloud Computing', 'assets/certificates/cloud-computing/azure-fundamentals-infosys.jpg', false, NULL, 130, true),

    -- Web Development Gallery & Featured
    ('Web Development Fundamentals', 'IBM SkillsBuild', 'Full-stack web development covering front-end technologies, responsive design, and modern deployment pipelines.', 'https://www.credly.com/badges/2977f3c8-acb9-4ad3-a4fb-37ce1220d25d/linked_in_profile', 'Web Development & Software', 'assets/certificates/web-development/web-dev-fundamentals-ibm.jpg', true, 'fas fa-code', 140, true),
    ('Front-End Web Development Internship', 'IBM SkillsBuild & Edunet Foundation', 'Front-End Web Development Internship certification.', NULL, 'Web Development & Software', 'assets/certificates/web-development/frontend-webdev-internship-ibm-edunet.jpg', false, NULL, 150, true),
    ('Website Development Tutorial', 'Infosys Springboard', 'Practical training in website layout and styling.', NULL, 'Web Development & Software', 'assets/certificates/web-development/website-dev-tutorial-infosys.jpg', false, NULL, 160, true);

    -- 3. Seed Badges
    INSERT INTO badges (title, issuer, issuer_icon, description, issue_date, expiry, expiry_icon, skills, image_url, credential_url, published, featured) VALUES
    ('Prepare Data for ML APIs', 'Google Cloud', 'fab fa-google', 'Hands-on labs on preparing data for ML APIs using Dataflow, DataProc, and AI APIs.', 'Apr 14, 2026', 'No Expiration', 'fas fa-infinity', ARRAY['Python', 'TensorFlow', 'Dataflow', 'DataProc', 'Vertex AI', 'ML'], 'assets/badges/prepare-data-ml-apis.png', 'https://www.credly.com/badges/d6534857-e7f5-49d5-be4c-d40a91e5cb48', true, true),
    ('Deep Learning using TensorFlow', 'IBM', 'fas fa-industry', 'Deep learning concepts including CNNs, RNNs, and autoencoders using TensorFlow.', 'Mar 30, 2026', 'No Expiration', 'fas fa-infinity', ARRAY['Deep Learning', 'TensorFlow', 'CNN', 'RNN', 'Autoencoders'], 'assets/badges/deep-learning-tensorflow.png', 'https://www.credly.com/badges/a289455e-4038-4810-a13d-f07613725b8b', true, true),
    ('IT Specialist – Artificial Intelligence', 'Certiport (Pearson VUE)', 'fas fa-graduation-cap', 'Validated expertise in AI fundamentals, ML concepts, and cloud-based AI solutions.', 'Dec 16, 2025', 'Expires Dec 2030', 'fas fa-clock', ARRAY['AI', 'Machine Learning', 'AWS', 'Azure'], 'assets/badges/it-specialist-ai.png', 'https://www.credly.com/badges/851d7a73-3caf-4851-baeb-52645964d1be', true, true),
    ('AWS Academy – Cloud Foundations', 'Amazon Web Services', 'fab fa-aws', 'AWS Cloud Foundations training covering core services, architecture, pricing & support.', 'Jan 10, 2025', 'No Expiration', 'fas fa-infinity', ARRAY['AWS Cloud', 'AWS Architecture', 'Core Services', 'Pricing'], 'assets/badges/aws-cloud-foundations.png', 'https://www.credly.com/badges/850a46b9-cd01-46eb-a853-35550567b86c', true, true),
    ('Web Development Fundamentals', 'IBM SkillsBuild', 'fas fa-industry', 'Web development principles including front-end, back-end, responsive design & deployment.', 'Oct 3, 2025', 'No Expiration', 'fas fa-infinity', ARRAY['HTML', 'CSS', 'JavaScript', 'DevOps', 'Responsive'], 'assets/badges/web-dev-fundamentals.png', 'https://www.credly.com/badges/2977f3c8-acb9-4ad3-a4fb-37ce1220d25d', true, true),
    ('Journey to Cloud: Envisioning Your Solution', 'IBM SkillsBuild', 'fas fa-industry', 'Cloud computing concepts, digital transformation strategies & enterprise design thinking.', 'Jul 16, 2025', 'No Expiration', 'fas fa-infinity', ARRAY['Cloud', 'Microservices', 'SaaS', 'PaaS', 'IaaS', 'API'], 'assets/badges/journey-to-cloud.png', 'https://www.credly.com/badges/85e4145d-ecb3-4b8f-bb30-e4e47b4a26cc', true, true),
    ('Getting Started with AI', 'IBM SkillsBuild', 'fas fa-robot', 'Comprehensive introduction to Artificial Intelligence concepts, ethical AI, and practical applications across industries.', '2025', 'No Expiration', 'fas fa-infinity', ARRAY['AI Fundamentals', 'Ethical AI', 'Applications'], 'assets/badges/getting-started-ai.png', 'https://www.credly.com/badges/de0e7fd4-8593-48c7-95f6-104af1769c4e', true, true);

    -- 4. Seed Internships
    INSERT INTO internships (role, company_name, duration, description, technologies, status, company_logo, published) VALUES
    ('AI & Machine Learning Internship', 'Averixis Solutions', 'Aug 2025 – Dec 2025', 'Built strong foundations in AI & ML concepts, applied learning through practical tasks, and developed problem-solving skills aligned with industry expectations. Recognized under AICTE.', ARRAY['AI', 'Machine Learning', 'AICTE', 'Problem Solving', 'Data Analysis'], 'Completed', 'assets/internships/aiml-averixis.jpg', true),
    ('Front-End Web Development Internship', 'Edunet Foundation & IBM SkillsBuild', '6 Weeks', 'Gained hands-on experience building responsive and interactive web pages, working with HTML, CSS, JavaScript, and modern frameworks. Strengthened UI/UX design principles and deployment skills. In collaboration with AICTE.', ARRAY['HTML', 'CSS', 'JavaScript', 'UI/UX', 'Responsive Design', 'IBM SkillsBuild'], 'Completed', 'assets/internships/frontend-edunet.jpg', true),
    ('Emerging Technologies — AI & Cloud', 'Edunet Foundation & IBM', '4 Weeks', 'Strengthened skills in AI and Cloud platforms while gaining hands-on exposure to real-world applications. In collaboration with AICTE and IBM.', ARRAY['AI', 'Cloud Computing', 'IBM', 'AICTE', 'Emerging Tech'], 'Completed', 'assets/internships/ai-cloud-edunet.jpg', true),
    ('UI/UX Design Internship', 'Snestron Systems Pvt. Ltd.', 'Jul 2025 – Aug 2025', 'Enhanced understanding of user-centered design and creative problem solving. Completed a 4-week online internship contributing meaningfully to design projects.', ARRAY['UI/UX', 'User Research', 'Prototyping', 'Design Thinking', 'Figma'], 'Completed', 'assets/internships/uiux-snestron.jpg', true),
    ('Web Development Internship', 'Abhimo Technologies', '2026', 'Contributed to full-stack web development projects, building and debugging PHP backends and JavaScript frontends across multiple client products.', ARRAY['PHP', 'JavaScript', 'MySQL', 'Full-Stack', 'Debugging'], 'Completed', 'assets/internships/abhimo.jpg', true);

    -- 5. Seed Projects
    INSERT INTO projects (title, short_description, full_description, technologies, skills, github_url, live_demo_url, project_image, featured, published, display_order, icon) VALUES
    ('Game Level Difficulty Balancer', 'An algorithmic solution that dynamically optimizes game difficulty curves using DAA principles — ensuring engaging, balanced gameplay.', 'Full implementation of priority queues, dynamic difficulty adjustment curves, and time complexity profiles to control gamer pacing in 2D platformers.', ARRAY['Python', 'Algorithms', 'DAA', 'Dynamic Programming'], ARRAY['Algorithm Design', 'Python'], 'https://github.com/sudeenjain/DAA-miniproject', NULL, NULL, false, true, 10, 'fa-gamepad'),
    ('Book Recommender System', 'An intelligent book recommendation engine built with Advanced Java that suggests titles based on user reading preferences and behavior patterns.', 'Includes content-based recommendations, user history vector models, and robust database support using JDBC.', ARRAY['Java', 'Advanced Java', 'Recommendation Engine'], ARRAY['Java'], 'https://github.com/sudeenjain/Adavanced-Java-BookRecommender', NULL, NULL, false, true, 20, 'fa-book'),
    ('IBM ML Recommender', 'A Python-based collaborative filtering system that leverages machine learning to predict user preferences and generate personalized recommendations.', 'Calculates cosine similarity and matrix factorization over high-density user reviews matrices.', ARRAY['Python', 'Machine Learning', 'Collaborative Filtering', 'IBM'], ARRAY['Machine Learning', 'Python'], 'https://github.com/sudeenjain/IBM-miniproject', NULL, NULL, false, true, 30, 'fa-cogs'),
    ('Interactive Recipe Finder', 'A dynamic web application enabling users to search, filter, and discover recipes with real-time ingredient matching and beautiful UI.', 'Uses external recipe search APIs, local storage caching, and sleek grid layout structure.', ARRAY['HTML', 'CSS', 'JavaScript', 'API Integration'], ARRAY['JavaScript', 'HTML/CSS'], 'https://github.com/sudeenjain/-interactive-recipe-finder', NULL, NULL, false, true, 40, 'fa-utensils'),
    ('Currency Converter', 'A real-time currency exchange tool that connects to live APIs — supporting 150+ currencies with instant conversion rates and clean interface.', 'Retrieves live exchange data from OpenExchangeRates API and stores currency mappings in custom visual lists.', ARRAY['JavaScript', 'REST API', 'Exchange Rates', 'Responsive'], ARRAY['JavaScript'], 'https://github.com/sudeenjain/currency-converter', NULL, NULL, false, true, 50, 'fa-exchange-alt'),
    ('Smart To-Do List', 'A Python-powered task management application with priority sorting, deadline tracking, and persistent storage for efficient productivity.', 'Uses JSON configuration file persistence, custom status updates, and priorities levels routing.', ARRAY['Python', 'File I/O', 'CLI', 'Task Management'], ARRAY['Python'], 'https://github.com/sudeenjain/to-do-list-in-python', NULL, NULL, false, true, 60, 'fa-tasks'),
    ('Gesture Flow', 'A gesture-controlled interface that interprets hand movements in real time to drive on-screen actions and interactions.', 'Processes raw camera footage inputs and maps points vectors using MediaPipe.', ARRAY['Python', 'Computer Vision', 'OpenCV'], ARRAY['Python', 'Machine Learning'], 'https://github.com/sudeenjain/guesture_flow', 'https://guestureflow.vercel.app/', NULL, false, true, 70, 'fa-hand-paper'),
    ('Attendance Tracker', 'A web-based attendance management system for recording, tracking, and reviewing attendance records efficiently.', 'Builds modular student visual charts, updates daily database fields, and provides tabular summaries.', ARRAY['JavaScript', 'Web App', 'Data Tracking'], ARRAY['JavaScript'], 'https://github.com/sudeenjain/attendence_tracker', 'https://attendance-tracker-eight-blush.vercel.app/', NULL, false, true, 80, 'fa-clipboard-check'),
    ('Movie Recommendation', 'A recommendation engine that suggests movies to users based on content similarity and viewing preferences.', 'Performs TF-IDF and bag-of-words vectorization on movies cast, directors, and genres columns.', ARRAY['Python', 'Machine Learning', 'Recommendation Engine'], ARRAY['Machine Learning', 'Python'], 'https://github.com/sudeenjain/Movie_Recommendation', 'https://movie-recommendation-plum-phi.vercel.app/', NULL, false, true, 90, 'fa-film'),
    ('Portfolio Website', 'An earlier version of this personal portfolio site, showcasing projects, certifications, and skills.', 'Static website built using responsive CSS grids, CSS custom variables, and basic interactive JS.', ARRAY['HTML', 'CSS', 'JavaScript'], ARRAY['JavaScript', 'HTML/CSS'], 'https://github.com/sudeenjain/portfolio', 'https://sudeenjain.github.io/portfolio/', NULL, false, true, 100, 'fa-user-circle'),
    ('FolioAI', 'An AI-powered portfolio assistant that helps generate and organize portfolio content automatically.', 'Allows users to customize section layouts and prompts LLMs to structure summary fields.', ARRAY['AI', 'JavaScript', 'Automation'], ARRAY['Artificial Intelligence', 'JavaScript'], 'https://github.com/sudeenjain/folioAI', 'https://portfolio-ai-eta-dusky.vercel.app/', NULL, false, true, 110, 'fa-robot'),
    ('CareerReady', 'A career-preparation platform helping users build job-readiness skills and track their progress.', 'Allows users to take mock aptitude tests and build custom resumes in real-time.', ARRAY['JavaScript', 'Web App', 'Career Tools'], ARRAY['JavaScript'], 'https://github.com/sudeenjain/CarrerReady', 'https://dist-steel-beta-55.vercel.app/#/landing', NULL, false, true, 120, 'fa-briefcase'),
    ('Product Recommendation', 'An AI-driven recommendation system that suggests products to users based on browsing and purchase behavior.', 'Performs user-based collaborative routing and groups products categories tags.', ARRAY['Python', 'AI', 'Recommendation Engine'], ARRAY['Machine Learning', 'Python'], 'https://github.com/sudeenjain/Product_Recommendation', 'https://ai-recommendation-system-gamma.vercel.app/', NULL, false, true, 130, 'fa-shopping-cart'),
    ('Connects The Dots', 'An algorithmic visualization project exploring graph connectivity and pathfinding concepts, built as a DAA mini-project.', 'Visualizes BFS, DFS, and Kruskal algorithms step-by-step.', ARRAY['Python', 'Algorithms', 'Graph Theory'], ARRAY['Algorithm Design', 'Python'], 'https://github.com/sudeenjain/Connect_the_Dots', 'https://daa-miniproject.vercel.app/', NULL, false, true, 140, 'fa-project-diagram'),
    ('Amazon Bestseller Recommender', 'A machine learning model that analyzes Amazon bestseller data to recommend similar high-performing products.', 'Performs exploratory data analysis on 10,000+ items and classifies them using random forests.', ARRAY['Python', 'Machine Learning', 'Data Analysis'], ARRAY['Machine Learning', 'Python'], 'https://github.com/sudeenjain/Amazon-Bestseller-Recommender', 'https://ibm-mini-project.vercel.app/', NULL, false, true, 150, 'fa-star'),
    ('AI Dictionary', 'An AI-powered dictionary tool offering smart word definitions, usage examples, and contextual understanding.', 'Interfaces with web APIs, processes NLP parameters, and parses dictionary definitions.', ARRAY['AI', 'NLP', 'JavaScript'], ARRAY['Artificial Intelligence', 'JavaScript'], 'https://github.com/sudeenjain/AI_dictonary', NULL, NULL, false, true, 160, 'fa-spell-check');

    -- Note: achievements list was empty under portfolio-data.js (only section was listed in html but no data items - wait, let's verify if there were achievements. If not, table can start empty)
